version: '3'
services:
    cloudflare-ddns:
        image: oznu/cloudflare-ddns:latest
        container_name: "Cloudflare_DDNS"
        restart: always
        environment:
            API_KEY: ${CLOUDFLARE_API}
            ZONE: ${CLOUDFLARE_ZONE}
            PROXIED: ${CLOUDFLARE_PROXIED}
    # PHP with usable version
    php:
        container_name: php
        build: ./php/
        working_dir: /code
        volumes:
            - ./config/php:/usr/local/etc/php/conf.d
            - ./www:/code
        depends_on:
            - mysql
        ports:
            - 9000:9000
    # Nginx
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./data/certificates:/etc/nginx/certificates
            - ./config/nginx:/etc/nginx/conf.d
            - ./www:/code
        restart: unless-stopped
        networks:
            public:
        depends_on: 
            - php
    # MariaDB database engine
    mysql:
        image: 'yobasystems/alpine-mariadb'
        container_name: 'mysql'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_CHARSET: utf8mb4
            MYSQL_COLLATION: utf8mb4_general_ci
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            public:
    # Database GUI
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        environment:
            PMA_HOST: mysql
        ports:
            - '8000:80'
        volumes:
            - ./config/phpmyadmin:/etc/phpmyadmin
        depends_on:
            - mysql
        networks:
            public:

networks:
    public:
        external: true